ARG install_dir=/opt/lotus

FROM {{ os_version }}

LABEL maintainer="O1.IO"
{% if system_dependencies|length > 0 %}

RUN {{ package_manager }} update -y && \
    {{ package_manager }} install -y {{ system_dependencies|join(' ') }}
{% endif %}

# Download and install prerequisite version of Go for build
RUN curl -L {{ go_url }} | tar -xzf - -C /tmp && ln -s /tmp/go/bin/go /usr/bin/go

RUN curl -L {{ archive_url }} | tar xzf - --strip-components=1 -C /usr/bin

COPY scripts/entrypoint.sh scripts/start-lotus.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh /usr/bin/start-lotus.sh
COPY entrypoints/setup-config.sh /entrypoint.d

ENTRYPOINT ["entrypoint.sh"]
CMD ["start-lotus.sh"]
